# Generated by Django 3.2.4 on 2021-07-06 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('end_date', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('note', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(max_length=100)),
            ],
        ),
    ]
