# Generated by Django 3.2.4 on 2021-07-06 11:14

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=django.contrib.auth.models.User, unique=True),
        ),
    ]
