# Generated by Django 3.2.4 on 2021-06-20 16:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(choices=[('label-success', 'high'), ('label-primary', 'medium'), ('label-danger', 'low')], max_length=100)),
                ('due_date', models.DateTimeField(default=datetime.datetime.now)),
                ('task_status', models.CharField(choices=[('not_started', 'not-started'), ('started', 'started'), ('halfway_done', 'halfway-done'), ('done', 'done')], default='not_started', max_length=100)),
                ('assigned_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
