# Generated by Django 3.2.4 on 2021-06-28 08:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_todos',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
